apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  labels:
    app: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: node-app
        image: pankajs53/nodejs-redis-queue-backend:v1
        ports:
        - containerPort: 3000
        volumeMounts:
        - mountPath: /app
          name: node-app-storage
        env:
        - name: PORT
          value: "3000"
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 30

      - name: redis-app
        image: redis:latest
        ports:
        - containerPort: 6379
        volumeMounts:
        - mountPath: /data
          name: redis-storage
        command: ["redis-server", "--appendonly", "yes", "--requirepass", "password"]
        readinessProbe:
          exec:
            command:
            - redis-cli
            - -a
            - password
            - ping
          initialDelaySeconds: 10
          periodSeconds: 10

      volumes:
      - name: redis-storage
        emptyDir: {}
      - name: node-app-storage
        emptyDir: {}
