apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
  labels:
    app: node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: pankajs53/nodejs-redis-queue-backend:v2
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: REDIS_HOST
          value: "redis-service"  # Name of the Redis service
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PASSWORD
          value: "password"      
